var artists = [
"Monet",
"Warhol",
"Rembrandt",
"Malevich",
"Gauguin",
"Kirchner",
"Caillebotte",
"Manet",
"Haacke",
"Duchamp",
"Dada",
"Picasso",
"Munch",
"Klimt",
"Delacroix",
"Goya",
"Durer",
"Giacometti",
"Wyeth",
"Matisse",
"Dali",
"Magritte",
"Miro",
"Kahlo",
"Pollock",
"Cassatt",
"Cezanne"
];

var filler1 = [
"a construct",
"a commentary",
"a critique",
"a criticism",
"a treatise",
"a discourse",
"a reflection",
"an exegesis",
"an exposition",
"a dichotomy",
"a contemplation",
"a meditation",
"a rumination",
"a cogitation",
"a musing",
"a study",
"a reflection",
"a reverie",
"an abstraction",
"an elucidation",
"an enucleation",
"a portal",
"a parallel",
"an analog",
"a comparison",
"a resemblance",
"an analogue",
"telling",
"evocative"
];

var filler2 = [
"gender bias & heteronormativity",
"breaking down the binaries",
"evocative postmodernism",
"kitsch and fetishism",
"German expressionist theory",
"the constructivist sentiment",
"an acute perspective of fauvism",
"a primitivist rendering",
"spacial depth and symmetry",
"the frenzied pace of city life",
"an abstraction of classism",
"ethereal synergism",
"the avant-garde philosophy",
"the withered self-representation"
];

var colors = [
"#CC0033",
"#3D4AA6",
"#578C1D"
];
