var artists = [
"Monet",
"Warhol",
"Rembrandt",
"Malevich",
"Gauguin",
"Kirchner",
"Caillebotte",
"Manet",
"Haacke",
"Duchamp",
"Dada",
"Picasso",
"Munch",
"Klimt",
"Delacroix",
"Goya",
"Durer",
"Giacometti",
"Wyeth",
"Matisse",
"Dali",
"Magritte",
"Miro",
"Kahlo",
"Pollock",
"Cassatt",
"Cezanne"
];

var filler1 = [
"a construct",
"a commentary",
"a critique",
"a criticism",
"a treatise",
"a discourse",
"a reflection",
"an exegesis",
"an exposition",
"a dichotomy",
"a contemplation",
"a meditation",
"a rumination",
"a cogitation",
"a musing",
"a study",
"a reflection",
"a introspection",
"a reverie",
"an abstraction",
"an elucidation",
"an enucleation",
"a portal",
"a parallel",
"an analog",
"a comparison",
"a resemblance",
"an analogue",
"telling",
"evocative"
];

var filler2 = [
"gender bias and heteronormativity",
"breaking down the binaries",
"evocative postmodernism",
"kitsch and fetishism",
"German expressionist theory",
"the constructivist sentiment",
"an acute perspective of fauvism",
"a primitivist rendering",
"spacial depth and symmetry",
"the frenzied pace of city life",
"a complex abstraction of classism",
"ethereal synergism",
"the avant-garde philosophy",
"the withered representation of self"
];

var colors = [
"#b8256f",
"#00cdd2",
"#f48700",
"#0800f4",
"#00f4bd",
"#ac4ae3",
"#674ae3",
"#ff6815",
"#26e5ba",
"#e5263a",
"#309c32",
"#eca681"
];
